# -*- coding: utf-8 -*-
{
    'name': 'Tazweed Core HR',
    'version': '16.0.2.0.0',
    'category': 'Human Resources',
    'summary': 'Core HR Management for UAE Manpower Companies',
    'author': 'Tazweed',
    'website': 'https://www.tazweed.com',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'hr',
        'hr_contract',
        'mail',
        'contacts',
    ],
    'data': [
        'security/tazweed_core_security.xml',
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'data/document_type_data.xml',
        'data/employee_category_data.xml',
        'views/hr_employee_views.xml',
        'views/employee_document_views.xml',
        'views/employee_bank_views.xml',
        'views/employee_sponsor_views.xml',
        'views/employee_category_views.xml',
        'views/document_type_views.xml',
        'views/dashboard_views.xml',
        'views/menu.xml',
        'wizard/document_wizard_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'tazweed_core/static/src/css/tazweed_core.css',
            'tazweed_core/static/src/js/dashboard.js',
            'tazweed_core/static/src/xml/dashboard_templates.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'sequence': 1,
}
